### ISSUE TITLE
Objectives & Key Results

### ISSUE THREAD

**Issue by chawang90** [josephine/handbook#19]
We tried and failed (sorry) at this last fall, although we might be ready to try again. Want to hear y'alls thoughts on [Objectives & Key Results as outlined by Clef](https://github.com/josephine/handbook/blob/master/Onboarding%20Documents/Objectives%20and%20Key%20Results.md). 

Full disclosure, the OKR definitions they set are pretty standard, and Clef hasn't quite gotten OKRs to 'work' yet either, but they're on their second quarter of trying to improve at them. 

I think some sort of goal setting should happen, open to other ideas or pared down/built up formats.

**Comment by talsafran** [comment]
> Objectives and Key Results (OKRs) is a method for defining and keeping track of goals and their outcomes. They organize our goals by breaking them into high-level aspirations (objectives) and the measurable results that determine whether or not we’ve reached them (key results). OKRs are set at the company and individual level to help everyone see how their personal goals align with Clef’s goals, and also see how other people in the organization are working for the same outcomes from a different perspective.

Other than changing Clef to Josephine (I just created a PR for that  in #35 :), this is :cool: 

> ## Examples
> 
> Objectives are the high level achievements you are shooting for, like:
> - Grow our audience in the Sacramento market
> - Onboard more cooks, faster!
> - Improve the first time experience of using Josephine (onboarding)
> - Speed up the test suite for our development team
> - Get more press
> - Develop better management skills
> 
> Key results are the measurable outcomes that define success for the objectives. **Key results must be measurable on a scale from 0-10**, so for the third example objective, the results might be:
> - Interview 20 users after they go through the onboarding experience (% completion)
> - Pick 3 places where we can make the biggest improvements and write specs for all three improvements by July 31 (-2 points for each day late)
> - Ship those improvements by September 15 (-3 points for each week late)
> - Increase conversion through signup process by 10%, starting at 50% (% completion)

^ I made some suggestions for changes here.

I can't say I _fully_ understand the scoring team. We start with 10 and deduct, sure... but what about the $ completion stuff? :confused: 

> ## Setting OKRs
> 
> Everyone at Clef sets their OKRs quarterly, writing them in the first week of the quarter and then evaluating them in the last week. At a startup it’s easy to focus on the immediate problems, but by setting our goals quarterly we ensure that everyone spends some time thinking about the challenges at least 3 months out.
> 
> Each person should set 3 to 5 objectives for the quarter, and each objective should have a maximum of 4 key results. Each objective also has a Description explaining what it means and an Alignment that explains how it aligns with company-wide goals. Each key result should explain how it will be scored at the end of the quarter.
> 
> For every quarter, one goal should always be a learning or improvement objective. It should describe some skill or area of knowledge you want to expand, and then the concrete steps that you will complete in order to succeed at learning or improving it.

I like this, especially that "one goal should always be a learning or improvement objective."

> Every employee should keep track of their OKRs in their own Google Spreadsheet in the OKRs Folder. Within the spreadsheet, there should be a new sheet for each new quarter.  
> 
> OKRS should be talked about every week in 1:1s to consider how each objective is progressing, places where help may be necessary, and how well they reflect current objectives.

Fsho.

> OKRs are scored at the end of the quarter, with a score generated for each Key Result. The average of the key results give a score for each Objective, and the average scores of the Objectives gives an overall score for the quarter.
> 
> A key result can be scored in any way that makes sense for the result, but there are a few common ways to score a Key Result:
> - **% completion** -- if the goal is to do some number of actions, or achieve some number of results (post 3 blog posts or get 300 views), then the Key Result can be scored according to the % that were completed. Posting 2 results out of 3 would earn a score of ⅔ x 10 (because 10 is the total possible number of points) or a 6.7.
> - **Due date** -- if a resource should be delivered on a given day, then a fixed number of points can be docked based on how many days late the resource is finished. The penalty should be set with the key result and should vary depending on how time-sensitive the result is. For instance, if my coworker needs me to finish something on time so that they can use it, then there should be a heavy penalty for being late. If the penalty for an item is -2 points per day, then finishing it 3 days late gives a score of 4.
> - **Deviation** -- if you are trying to hit a precise target, and do not want to go above or below it, then the score can be based on how far off you were.
> 
> The scoring method should be included with each key result. If two people independently evaluated your OKRs at the same time, they should be sure to get the same scores because the criteria for evaluation should be unambiguous.
> 
> OKRs should never be used in evaluating employee performance, and should be ambitious. An average score of 7 is ideal, and no one should ever get to a full 10. If they do, their goals were set too low.

Ahhhh okay I understand the scoring now. This is chill.

**Comment by sike13** [comment]
I also think it's worthwhile to give OKRs another go. It would be lovely to have more quantitative data to point to when we're reviewing a quarter. That said, I think we need to have more structure to OKR check-ins — I don't think 1:1s are the appropriate place to talk about OKRs since those conversations tend to be more emotional. Maybe a bi-monthly check-in by team? All-hands check-in once a month?

**Comment by talsafran** [comment]
Bi-monthly team meeting makes a lot of sense.

All hands –– what do you think the goal of that would be?

On Wed, Jan 13, 2016 at 2:39 PM, Sika Gasinu notifications@github.com
wrote:

> I also think it's worthwhile to give OKRs another go. It would be lovely
> to have more quantitative data to point to when we're reviewing a quarter.
> That said, I think we need to have more structure to OKR check-ins — I
> don't think 1:1s are the appropriate place to talk about OKRs since those
> conversations tend to be more emotional. Maybe a bi-monthly check-in by
> team? All-hands check-in once a month?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/josephine/handbook/issues/19#issuecomment-171459929.

## 

josephine.com // @talsafran http://twitter.com/talsafran

**Comment by sike13** [comment]
@talsafran I was thinking one or the other. Benefit of all-hands is that every team will have a sense of how other teams are doing and/or can offer support in whatever way they can. For example, if the Cook Team isn't meeting onboarding OKRs because there aren't enough leads, Growth can step in and help the Cook Team reach their OKRs, which helps the whole company. I like the idea of this being collaborative as opposed to everyone operating in their own lanes to get to the common goal.

**Comment by talsafran** [comment]
Word. So maybe we alternate?

Week 1 – Team
Week 3 – All Hands
Week 5 – Team
etc...

On Wed, Jan 13, 2016 at 2:44 PM, Sika Gasinu notifications@github.com
wrote:

> I was thinking one or the other. Benefit of all-hands is that every team
> will have a sense of how other teams are doing and/or can offer support in
> whatever way they can. For example, if the Cook Team isn't meeting
> onboarding OKRs because there aren't enough leads, Growth can step in and
> help the Cook Team reach their OKRs, which helps the whole company. I like
> the idea of this being collaborative as opposed to everyone operating in
> their own lanes to get to the common goal.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/josephine/handbook/issues/19#issuecomment-171461133.

## 

josephine.com // @talsafran http://twitter.com/talsafran

**Comment by joyjding** [comment]
The team, allhands structure seems pretty cool. I have mixed feelings about OKRs, as often, they are written, and then not reviewed until the end of the quarter. If OKRs are to be useful, everyone needs to know about everyone else's OKRs, and we need to be reviewing them frequently.

**Comment by terrybetts24** [comment]
If this is not a performance measurement tool, then OKR's are for creating a work plan? Do they ever tie in to performance? How do we then measure performance? 

"OKRs should never be used in evaluating employee performance, and should be ambitious. An average score of 7 is ideal, and no one should ever get to a full 10. If they do, their goals were set too low."

**Comment by egustafson5** [comment]
I'm definitely in favor of clear goal setting and regular check-ins, both within and across teams. Agnostic as to whether this is OKRs or some other structure. I like the alternating team/all-hands check-ins. 

One thing that I think we should account for in our OKRs assessment is the trade-offs that often happen given our resource limitations, shifting priorities, and unexpected challenges that come up. We might get a horrible "score" on one of our OKRs, because something (e.g. legal) came up unexpectedly and we dealt with that instead, which may be an overall win for the team and for the company. We should somehow acknowledge and account for that when we're assessing and/or setting these OKRs.

**Comment by chawang90** [comment]
@talsafran the "one goal should always be a learning or improvement objective." is Clef specific - its' another manifestation of their 'be better today than you were yesterday' value. I'm cool with it as well, but I generally don't like copying the parts of the handbook that they wrote specifically for their team and their values. 

@egustafson5 @talsafran @joyjding @sike13 No right or wrong answers for cadence on check in. My vote is for smaller, more nimble check ins amongst each team bi-monthly and then have team leaders summarize and post progress/set backs maybe in a slack channel or something for everyone to see? Fine will all hands as well, imagine that would look like a round table one at a time update type of meeting?

@terrybetts24 OKRs are meant as a goal setting tool. on one hand it lets people set goals and measure their progress against them, but on the second hand it allows for the organization to have goals that are representative of the sum of its' employees' and teams' goals.

Performance measurement at Josephine should always be a much more nuanced conversation since our impacts are more complex than any one metric of output/improvement. 

It's a good question though, @josephine/team-josephine how do you all think we should approach performance assessment? Clef has dodged the question by saying the company is small enough to handle on a case by case basis and I somewhat tend to agree for Josephine. I think that the purpose of 1:1s and retros and our commitment to honest and emotionally vulnerable communication is so that we can identify issues between our relationships with Josephine as an entity and address them proactively.

**Comment by chawang90** [comment]
@MattJorgensen you're onboard with OKRs, I'm assuming? @zeke any experience with this type of stuff from past companies?

**Comment by MattJorgensen** [comment]
Hi @josephine/team-josephine --

Along the lines of Emily's comment earlier about "the trade-offs that often happen given our resource limitations, shifting priorities, and unexpected challenges that come up" -- I'm wondering if it might make the most sense to set OKRs at a team level ? 

My proposal for using our initiatives and setting tangible goals would be: 
- Quarterly initiatives list by team (just a complete download of what we did earlier this week) + OKRs also at a team level -- two tabs in same spreadsheet https://docs.google.com/spreadsheets/d/1HMse_dQXt-BXiQHd31DkwDGFjdZ__FkWQLqoz5-GnbE/edit#gid=485941023
- 30-days-out prioritizations by team that can be kept track of in a Trello Board or whatever publicly viewable format is preferred by each team. Individual task owners probably make sense for business/cook teams, may not for product team? These can be re-prioritized at or after the bi-weekly OKR check-ins (I like the alternating Team/ All-Hands Format) https://trello.com/b/mLk5wq9t/business-team-q1-2016-roadmap
- Weekly prioritization / sprint planning like we already do by team 

Thoughts? Would love to have OKR-setting done by mid-next-week!

**Comment by chawang90** [comment]
raw notes, disregard for now.

'we're not formally including personal goal setting in the team organization and prioritization process but we do encourage each member of the team to set personal goals at the same time and discuss them with their manager and review them during 1:1s.'

1:1s are personal development best forum to be discussing those types of things. trying to separate personal emotional development and performance orient goal setting. 

OKRs are about what's best for the company overall. 

we'll create more formal personal goal documentation as we grow as a team.

**Comment by chawang90** [comment]
A couple points here:
1. We're missing personal/development oriented OKRs, which I think are important and should be written down, measured, and discussed. The question would be where we document that, and when we measure and discuss. 
2. Not setting personal OKRs is something that will only work for a short while. As the teams grow bigger the need for individual accountability will surely surface.

**Comment by chawang90** [comment]
latest doc for review [here](https://github.com/josephine/handbook/blob/master/Onboarding%20Documents/Objectives%20and%20Key%20Results.md)

**Comment by MattJorgensen** [comment]
These look great. No more comments. 

We should get recurring meetings set to check-in on OKRs with team and all-hands

**Comment by terrybetts24** [comment]
I liked the structure of the biz dev/cooks team mtg today where we walked through the OKR's as they relate between the two teams. Staying on track with the check ins and with quarter end evaluations (specifically to the cooks team and then in combo with biz dev), should be a priority so this good work doesn't go astray. Can we plot out regular meetings asap for the rest of the quarter?
