### ISSUE TITLE
Sourcing Candidates

### ISSUE THREAD

**Issue by MattJorgensen** [josephine/handbook#23]
I like this section in theory, but feel like ours could be punchier and specifically relevant to the Josephine brand. 

Specifically, how do we go about building an internal team that reflects the demographics of the communities we are serving? Is that important to us? What type of team backgrounds reflect Josephine values (e.g. combination of private and non-profit sectors? combination of health and food and tech backgrounds?)

This section can help future employees understand why they've joined such a bomb team and how they can contribute to growing it right :)

**Comment by chawang90** [comment]
Had duplicate issue, migrating my thoughts here. 

[Here is the sourcing candidates doc with minimal changes](https://github.com/josephine/handbook/blob/master/Operations%20Documents/Sourcing%20Candidates.md)

I think we can improve by rewriting our diversity and inclusion approach from the perspective of being representative of the community we serve

Also we currently use Streak instead of Workable, haven't checked out Workable but worth a peep.

**Comment by talsafran** [comment]
> Building a great team starts with attracting great candidates, and there are three channels we can use to attract candidates: referrals, outbound recruiting, and inbound interest. We should keep all three channels open, but be thoughtful about the biases that result from each channel so that we can make them work for our team-building goals and values.

^ Sure.

> Referrals from people who already work at Josephine are one of the best signals we can get about whether or not a candidate will be successful at Josephine. Josephine employees understand Josephine’s needs and what it’s like to work at Josephine, and their relationship with the candidate means they know a lot more than we can learn during an interview process.
> 
> In order to get good referrals, everyone needs to know which positions are open, know how to start the recruiting process, have time to search their network, and feel aligned with the company incentives. Open positions should be posted on josephine.com/jobs and also in the #hiring channel so that everyone sees who we’re trying to hire. We’ll host a company lunch with food on the second Tuesday of every month where we talk about which positions are open and go through everyone’s online networks looking for and thinking about candidates. Employees will do initial outreach to interesting connection, which will give us a good space to talk about how we start the recruiting process.

I like the idea of a once-a-month company lunch (or some meeting... but catering lunch is a better use of time and more fun) to focus on hiring together. This could mean searching our own networks, or going on the offensive on (for technical hires) sites like [Angellist](http://angel.co), [Rails Jobs](http://rails.jobs.com), or any of the sites from my friend Evadora's [diversity list](http://www.railsjobs.com/).

Agree that the copy above is long, but don't see a real reason to edit anything out.

> All of our job openings and descriptions will be posted on josephine.com, and some will be posted on other sites where we can advertise our open positions. Careful thought should be given to where we post job openings, as traditional boards have homogeneous audiences. We will also have people reading about Josephine through our blog and social media, developers working with our tools and participating in our community, and a broad audience hearing about Josephine through news or using the product.
> 
> Inbound applications give us the highest number of candidates that are outside of our personal networks, but also have the lowest initial filter because no one at Josephine is making any judgment about the candidate before they enter our pipeline. Because of the light filter, it can be tempting to dismiss these candidates, but an inbound application is a strong signal that the candidates believe in what we’re doing at Josephine. This means that a smaller percentage of candidates from a broader pool will progress through our interview funnel.
> 
> As an initial filter, inbound applications have the lowest quality check because no one at Josephine is making any judgment about the candidate before they enter our pipeline. However, an inbound application is a strong signal that the candidates believes in what we’re doing at Josephine. This means that a smaller percentage will progress through our interview funnel, but that we still need to treat these candidates with respect.

Yep. Pretty verbose – not sure if there's value to editing this out but it's essentially saying where inbound can be good and where it can be bad.

> Every inbound application should receive a response from the Josephine team within 3 days so that they feel heard and like they were able to reach us personally.

I've been bad at the 3 business days thing recently, but once I get a handle on the process (and canned responses etc) then cool.

> Note: We use Workable to manage candidates, but when you "Disqualify" a candidate on Workable, it does not send the candidate an email or let them know that they have been disqualified. You should always send the candidate an email before you Disqualify them.

Can delete this.

**Comment by sike13** [comment]
Totally agree with Matt here. I think a big part of what the sourcing leads article is missing (totally because Clef and Josephine are very different companies) is the fact that our leads have to fulfill both needs at Josephine HQ also needs among the broader Josephine community (our cooks and customers). Probably a good place to reiterate that we want our hires to mirror our community as well.

**Comment by joyjding** [comment]
I really like these questions:

> Specifically, how do we go about building an internal team that reflects the demographics of the communities we are serving? Is that important to us? What type of team backgrounds reflect Josephine values (e.g. combination of private and non-profit sectors? combination of health and food and tech backgrounds?)

and  I think we need to articulate **why** it's important to us as team, but also, what impact that has on being able to serve our communities. More than diversity for diversity's sake (and there are a lot of arguments for these!), diversity as part of **Josephine** strategy and company makeup. 

Another way to phrase this is: why is diversity a part of our dna?

**Comment by egustafson5** [comment]
I don't have much else to add. In agreement with everyone! Maybe add something about sourcing candidates from our various community partners (either people who previously worked for/with them, or people our partners know & love)?

**Comment by chawang90** [comment]
We could probably lift this from job descriptions and flesh it out a little: 
**We know that our ability to serve a community hinges in part on our ability to be representative of it - not just as a company, but as individuals with unique perspectives.**

Channels we prefer - our own cook community, partnering organizations, local food and labor justice non-profits, and job groups/communities with the specific aim of creating representative applicant pools (There are a slew of these for diverse communities & companies taking diversity seriously)

**Comment by chawang90** [comment]
latest updates for review [here](https://github.com/josephine/handbook/blob/master/Operations%20Documents/Sourcing%20Candidates.md)

**Comment by MattJorgensen** [comment]
Also great, no more comments. Much improved.

**Comment by terrybetts24** [comment]
Nothing to add.
