### ISSUE TITLE
Mission Statement 2.0 

### ISSUE THREAD

**Issue by chawang90** [josephine/handbook#31]
Missions as currently stated are [here](http://josephine.com/mission). Question is if we should write a more marketing friendly version of it.

> Our mission at Josephine is threefold:
> 
> **Labor**
> We believe in creating more inclusive opportunities in food for people who need it the most - stay at home parents, immigrants, and people of underrepresented minority groups. Cooking is the most fundamental lever of economic empowerment, and the food industry has taken that away through its strict barriers to entry.
> 
> **Food Justice**
> We seek to increase access to healthy food options, specifically in areas suffering from issues like food deserts. Home cooking can empower healthy decision-making in communities that haven’t had the privilege of nutritional education - the appeal of home cooking exists across all cultures and geographies. Home cooking also allows for the decolonization of ethnic foods by making sure that cooks and communities are directly benefiting from their own food and culture.
> 
> **Tech Equity**
> We want to contribute to a more diverse and inclusive tech culture. Our platform serves everyone from ESL immigrants to mothers and retirees – not all of whom have computers or are comfortable with smartphone apps. We try to not only lead through example, but also to acknowledge and mitigate our displacing effect through support of initiatives and organizations that are building a more inclusive tech ecosystem.

**Comment by chawang90** [comment]
I do feel like what we have on the site now is the most direct and succinct way for us to illustrate our mission, and that rewriting it may risk making it too fluffy.

**Comment by joyjding** [comment]
That's fine by me. Does that mean we can close this issue?

**Comment by joyjding** [comment]
While I don't think that we need to re-articulate our mission to make it more marketing-friendly, I do think that there needs to be better succinct ways to articulate what Josephine is. A one liner, a two liner, and a paragraph version would be super helpful. These can be more marketing-y.

**Comment by sike13** [comment]
Agreed with @joyjding — I think that what we have right now, plus a more easily digestible version is ideal. That said, if there's no way to distill the three aspects of the mission w/o it being fluffy, I say we leave it as is minus this edit:

From this:

> We seek to increase access to healthy food options, specifically in areas suffering from issues like food deserts.

To this:
We seek to increase access to healthy food options, particularly in [food deserts](http://americannutritionassociation.org/newsletter/usda-defines-food-deserts).

**Comment by joyjding** [comment]
Sika! I'm soooooo glad that you pointed this out. This has been a snail
poop on my foot in the mission for WEEKS. I personally took it out of each
job posting cuz it's squirmy feeling.

**Comment by egustafson5** [comment]
agreed. mission statements are good, and not convinced we have a clear vision on how to improve them, so any adjusting would likely make them muddier. 

@sike13 +1 for that edit. 
@joyjding +1 for one and two liners. and paragraph form. something for our BD & Comms human to do :)

**Comment by terrybetts24** [comment]
Agreed with all of the above.

Love this as another aspect of justice: "Home cooking also allows for the decolonization of ethnic foods by making sure that cooks and communities are directly benefiting from their own food and culture."

**Comment by chawang90** [comment]
[Updated Mission Statement](https://github.com/josephine/handbook/blob/master/Mission%20Statement.md)
